spring.application.name=EasyF1

spring.datasource.url=jdbc:postgresql://localhost:5432/database
spring.datasource.username=postgres
spring.datasource.password=postgres

api.security.token.secret=burriceminha